# SPDX-FileCopyrightText: 2023 Urs Fleisch <ufleisch at users.sourceforge.net>
# SPDX-License-Identifier: CC0-1.0

include:
  - project: sysadmin/ci-utilities
    file:
      - /gitlab-templates/linux.yml
      - /gitlab-templates/linux-qt6.yml
#      - /gitlab-templates/freebsd.yml
#      - /gitlab-templates/windows.yml
      - /gitlab-templates/flatpak.yml
