# SPDX-FileCopyrightText: 2023 Urs Fleisch <ufleisch at users.sourceforge.net>
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux/Qt5', 'FreeBSD/Qt5']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/kconfig': '@stable'
    'frameworks/kconfigwidgets': '@stable'
    'frameworks/kcoreaddons': '@stable'
    'frameworks/kio': '@stable'
    'frameworks/kwidgetsaddons': '@stable'
    'frameworks/kxmlgui': '@stable'
- 'on': ['Linux/Qt6', 'FreeBSD/Qt6']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kconfig': '@latest-kf6'
    'frameworks/kconfigwidgets': '@latest-kf6'
    'frameworks/kcoreaddons': '@latest-kf6'
    'frameworks/kio': '@latest-kf6'
    'frameworks/kwidgetsaddons': '@latest-kf6'
    'frameworks/kxmlgui': '@latest-kf6'

Options:
  use-ccache: True
  cmake-options: '-DWITH_CHROMAPRINT=OFF -DWITH_READLINE=OFF'
  require-passing-tests-on: [ '@all' ]
  run-cppcheck: True
  run-gcovr: False
